project:
  type: website

website:
  title: "2022 Masters' program boot camp"
  navbar:
    left:
      - text: Home
        url: index.qmd
      - text: Backgrounding
        url: backgrounding.qmd
      - text: Public records
        url: pubrecords.qmd
      - text: Spreadsheets
        url: spreadsheets.qmd 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



